#!/bin/sh
i=$1
[ ! -d "$i" ] && exit
echo $i | grep -q '^0' && exit
echo "$i" 
cd $i
pb=${i}.petbuild
sed -e s'%\${ARCH}%\${ARCH}_\${BUILD}%g' \
		-e s'%\.\.\/\${PKG}\-install%\.\.\/\${PKG}\-install \$BUILD%'  \
		-e s'%^CWD=%BUILD=slk600\nCWD=%'< $pb > ${pb}.new
if grep -q '\$PKG\-\$VER\-\$ARCH\/' $pb;then
	sed -e s'%\$PKG\-\$VER\-\$ARCH\/%\${PKG}\-\${VER}\-\${ARCH}_\${BUILD}\/%g' < $pb > ${pb}.new
fi
#if grep -q 'find \.\/\$PKG\-\$VER\-\$ARCH\/' $pb;then
	#sed -e s'%\$PKG\-\$VER\-\$ARCH%\${PKG}\-\${VER}\-\${ARCH}_\${BUILD}%' < $pb > ${pb}.new
#fi
#sed -e 's%^CWD=%BUILD=slk600\nCWD=%' < $pb > ${pb}.new
